name: ModSims
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - eigen=3.4.0
  - hdf5=1.14.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - libaec=1.0.6
  - libcurl=8.3.0
  - libedit=3.1.20191231
  - libev=4.33
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libnghttp2=1.52.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libzlib=1.2.13
  - mpi=1.0
  - ncurses=6.4
  - openmpi=4.1.5
  - openssl=3.1.3
  - zlib=1.2.13
  - zstd=1.5.5
