name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - beautifulsoup4=4.12.2
  - binutils_impl_linux-64=2.40
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - catch2=3.4.0
  - certifi=2023.7.22
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cmake=3.27.6
  - colorama=0.4.6
  - conda=23.7.4
  - conda-build=3.26.1
  - conda-index=0.2.3
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.4
  - eigen=3.4.0
  - filelock=3.12.4
  - gcc=13.2.0
  - gcc_impl_linux-64=13.2.0
  - glob2=0.7
  - gxx=13.2.0
  - gxx_impl_linux-64=13.2.0
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - jinja2=3.1.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libaec=1.0.6
  - libarchive=3.7.2
  - libcurl=8.3.0
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblief=0.12.3
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libsanitizer=13.2.0
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libuv=1.46.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.3
  - more-itertools=10.1.0
  - mpi=1.0
  - ncurses=6.4
  - openmpi=4.1.5
  - openssl=3.1.3
  - packaging=23.1
  - patch=2.7.6
  - patchelf=0.17.2
  - pip=23.2.1
  - pkginfo=1.9.6
  - pluggy=1.3.0
  - psutil=5.9.5
  - py-lief=0.12.3
  - pybind11=2.11.1
  - pybind11-global=2.11.1
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-libarchive-c=5.0
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - rhash=1.4.4
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.33
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.2.2
  - six=1.16.0
  - soupsieve=2.5
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.66.1
  - tzdata=2023c
  - urllib3=2.0.5
  - wheel=0.41.2
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.21.0
  - zstd=1.5.5
  - pip:
      - contourpy==1.1.1
      - cycler==0.11.0
      - fonttools==4.42.1
      - iniconfig==2.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - numpy==1.26.0
      - pillow==10.0.1
      - pyparsing==3.1.1
      - pytest==7.4.2
      - python-dateutil==2.8.2
