name: ModSims
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - eigen=3.4.0
  - hdf5=1.14.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libaec=1.0.6
  - libcurl=8.3.0
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - mpi=1.0
  - ncurses=6.4
  - openmpi=4.1.5
  - openssl=3.1.3
  - pip=23.2.1
  - pybind11=2.11.1
  - pybind11-global=2.11.1
  - python=3.11.5
  - python_abi=3.11
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - contourpy==1.1.1
      - cycler==0.11.0
      - fonttools==4.42.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - numpy==1.26.0
      - packaging==23.1
      - pillow==10.0.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - six==1.16.0
